theme: jekyll-theme-minimal
title: Pagina Web Laboratorio
description: Esta es una página web creada por el Laboratorio de Hidráulica de la Facultad Regional Córdoba. Usted podrá visualizar las precipitaciones máximas diarias para cada periódo de recurrencia para gran parte de la República Argentina seleccionando los mapas correspondientes.
logo: Taughannock.jpg
#You can also add a logo from an image URL, as below
#logo: https://www.lawschool.cornell.edu/_cs_apps/pt_photo_gallery/uploads/mainphotogallery/fullsizeimage/Photogallery_Ithacapage_8.png
