theme: jekyll-theme-cayman
title: [Pagina Web Laboratorio]
description: [Esta es una página web creada por el Laboratorio de Hidráulica de la Facultad Regional Córdoba. Usted podrá visualizar las precipitaciones máximas diarias para cada periódo de recurrencia para gran parte de la República Argentina seleccionando los mapas correspondientes]
logo: 240px-UTN_logo.jpg

